name: spam-email-replier

on:
  push

jobs:
  ci:
    runs-on: ubuntu-20.04
    timeout-minutes: 10
    strategy:
      matrix:
        node-version: [14, 16]
    steps:
    - name: Checkout ${{ github.sha }}
      uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      run: npm ci
    - name: Lint
      run: npm run lint --if-present
    - name: Build
      run: npm run build --if-present
    - name: Test
      run: npm run test --if-present